New Dataset superclass
matsengrp/netam pull request #89
Opened 2024-11-22 01:00 UTC by willdumm

This ended up being a pretty small PR, consolidating some branch lengths-related code into a new superclass `BranchLengthsDataset` as suggested in #55. Before merge I'll spend a bit more time looking for other duplication that can be resolved in this way.

Will close #55

2024-11-22 21:13 UTC, matsen approved these changes
👍

2024-11-22 23:35 UTC, willdumm commented
@matsen I also addressed #22, by moving some methods and functions around. All pre-existing functions and methods should work as they did before.

2024-11-22 23:38 UTC, matsen approved these changes

2024-11-24 17:44 UTC, matsen requested changes
I appreciate what you're doing here, but there's something that doesn't quite make sense.

The `ModelBase` covers all sorts of models, e.g. SHM models, so it doesn't make sense for it to have a method `selection_factors_of_sequences`. We could call it something generic like `evaluate_sequences`, as long as all the components will make sense for SHM models and DXSM models.

2024-11-24 17:44 UTC, matsen commented on netam/models.py
> +        device = next(self.parameters()).device
Let's make this a `@property` .

2024-11-25 21:50 UTC, willdumm commented
Changed `selection_factors_of_sequences` to `evaluate_sequences` and added device property to `ModelBase` and `AbstractBinarySelectionModel`.

2024-11-26 16:16 UTC, matsen approved these changes

2024-11-26 18:03 UTC, merged